# Generated by Django 4.1 on 2022-08-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCartApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseimage', models.ImageField(max_length=255, upload_to='img/')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
