# Generated by Django 4.1 on 2022-08-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCartApp', '0003_tutorials'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorials',
            name='links',
            field=models.CharField(default='', max_length=10),
        ),
    ]
