# Generated by Django 4.1 on 2022-08-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCartApp', '0004_tutorials_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorials',
            name='notes',
            field=models.ImageField(default='', max_length=255, upload_to='files/'),
        ),
    ]
