# Generated by Django 4.1 on 2022-08-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCartApp', '0005_tutorials_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='notes',
            field=models.FileField(default='', max_length=255, upload_to='files/'),
        ),
    ]
