# Generated by Django 4.1 on 2022-08-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduCartApp', '0006_alter_tutorials_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorials',
            name='notes',
        ),
    ]
