# Generated by Django 4.1 on 2022-08-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduCartApp', '0007_remove_tutorials_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='links',
            field=models.CharField(default='', max_length=40),
        ),
    ]
